[workspace]
authors = ["Denis Sergeev <dennis.sergeev@gmail.com>"]
channels = ["conda-forge"]
name = "exo_lightning"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.7,<3.14"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.10.6,<4"
numpy = ">=2.3.3,<3"
iris = ">=3.13.1,<4"
pandas = ">=2.3.3,<3"
aeolus = ">=24.11.1.2,<25"
ipykernel = ">=6.30.1,<7"
numba = ">=0.62.1,<0.63"
